// Angular/learn-angular/src/app/layout/mainlayout/mainlayout.component.ts
import { MainComponent } from './../main/main.component';
import { Component } from '@angular/core';
import { HeaderComponent } from '../header/header.component';
import { FooterComponent } from '../footer/footer.component';
import { MenuComponent } from '../menu/menu.component';

@Component({
  selector: 'app-mainlayout',
  standalone: true,
  imports: [HeaderComponent,FooterComponent, MenuComponent,MainComponent],
  templateUrl: './mainlayout.component.html',
  styleUrl: './mainlayout.component.css'
})
export class MainlayoutComponent {

}

<div class="MainLayout">
  <header>
    <app-header />
  </header>
  <aside>
    <app-menu />
  </aside>
  <main>
    <app-main />
  </main>
  <footer>
    <app-footer />
  </footer>
</div>

// Project3/tosend/v1/frontEnd/trip-app/src/Components/Layout/MainLayout/MainLayout.tsx
import { MainRoute } from '../../Routes/mainRoute/mainRoute';
import { Footer } from '../Footer/Footer';
import { Header } from '../Header/Header';
import { Menu } from '../Menu/Menu';
import './MainLayout.css';

export function MainLayout(): JSX.Element {
  return (
    <div className='MainLayout'>
      <header>
        <Header />
      </header>
      <aside>
        <Menu />
      </aside>
      <main>
        <MainRoute />
      </main>
      <footer>
        <Footer />
      </footer>
    </div>
  );
}
